### ISSUE TITLE
Review licenses for all artwork

### ISSUE THREAD

**Issue by fstonedahl** [AugustanaCSC490Spring2015/SealTeamSixGame#1]
Find or create new artwork to replace any art assets that are not public domain / creative commons / or otherwise legally licensed.

**Comment by ghost** [comment]
This list accounts for all art assets currently used:
- [Menu Picture](http://www.publicdomainpictures.net/view-image.php?image=113744&picture=playing-cards) - Public Domain
- [Playing cards](https://code.google.com/p/vector-playing-cards/) - Public domain
- End Cup animation - I am using the assign function so Lindsey can verify if she made this animation or what license it was found under

**Comment by lnicolaysen** [comment]
I made the cup animation myself
