### ISSUE TITLE
Disclaimer content and frequency

### ISSUE THREAD

**Issue by ghost** [AugustanaCSC490Spring2015/SealTeamSixGame#3]
As discussed in class, we want the disclaimer to only show on the first use, not before every game. It would also be wise to double-check what it is actually disclaiming and verify if that is enough or if we should expand on it.

**Comment by fstonedahl** [comment]
This is a very good point.  Drinking games pose certain threats above and beyond regular social/casual drinking, and can put unreasonable pressure on participants to drink at the level of "binge drinking", leading to serious health concerns.  Women and people who are underweight are also at a disadvantage in these games.  These threats/concerns need to be addressed. 

A few possible references:
http://www.indiana.edu/~engs/articles/games.html
http://www.cosmopolitan.com/health-fitness/advice/a2845/drinking-facts/

In fact, I would recommend that the game have built-in reminders (after each X number of rounds of game play) to make sure everyone is feeling okay... total up how much each person has drunk thus far, (and perhaps check the BAC calculator?) perhaps take a stretch break, or perform some kind of coordination task to judge the level the inebriation.

**Comment by fstonedahl** [comment]
Also: http://www.stuff.co.nz/national/crime/624707/Circle-of-death-drinking-game-led-to-fatal-crash

(Although the drinking game itself is not specifically at fault here... it's clearly the fact that they were driving afterward.  The only possible blame toward the game would be if they had driven there not expecting to drink enough to be dangerous, but got involved in the game, and ended up drinking a lot more than they had meant to.)

And a more general ref.

http://educalcool.qc.ca/en/alcohol-and-you/young-people/drinking-games-can-be-deadly/#.VT5KPh-c1N0

**Comment by ghost** [comment]
I have set the disclaimer to only show on the first launch in app. I added the help wanted tag so we can discuss if we want to change the disclaimer content in class.

**Comment by ghost** [comment]
Fixed a while back
