### ISSUE TITLE
Play again button on Game Over screen does not work

### ISSUE THREAD

**Issue by ghost** [AugustanaCSC490Spring2015/SealTeamSixGame#9]
This has not yet been coded

**Comment by caitlinloney** [comment]
New game starts but players are still rule masters from previous game

**Comment by ghost** [comment]
Caitlin is working on this and will assign to Christian to reset the "Question master" like titles

**Comment by caitlinloney** [comment]
I fixed the issue by adding a for each loop in the GameOverActivity.java class, setting each of the three rule masters as false for each player (under the comment // remove rule masters from players)
